image: node:20

stages:
  - deploy

pages:
  stage: deploy
  script:
    - npm ci
    - BASE_PATH="/${CI_PROJECT_NAME}/" npm run build
    - rm -rf public
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    - master
